model:
  init_args:
    evaluator_cfg:
      fit:
        class_path: torchmetrics.MetricCollection
        init_args:
          metrics:
            PR-AUC:
              class_path: torchmetrics.AveragePrecision
              init_args:
                task: binary
            F1:
              class_path: torchmetrics.F1Score
              init_args:
                task: binary
            ROC-AUC:
              class_path: torchmetrics.AUROC
              init_args:
                task: binary
            stat:
              class_path: torchmetrics.ClasswiseWrapper
              init_args:
                labels: [tp, fp, tn, fn, support]
                metric:
                  class_path: torchmetrics.StatScores
                  init_args:
                    task: binary
      val:
        - {}
        - {}

trainer:
  callbacks:
    change_item:
      - - 0
        - init_args:
            monitor: val/ROC-AUC_1
            filename: "epoch:{epoch}-val_f1_1:{val/F1_1:.4g}-val_pr_auc_1:{val/PR-AUC_1:.4g}-val_roc_auc_1:{val/ROC-AUC_1:.4g}.ckpt"
            mode: max
